version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/app"
      - "bundle_cache:/usr/local/bundle"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: rails_learning_development
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_learning_development
    volumes:
      - "mysql_data:/var/lib/mysql"

  redis:
    image: redis:7
    volumes:
      - "redis_data:/data"

volumes:
  bundle_cache:
  mysql_data:
  redis_data:
